# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NativeIntegrationExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeIntegrationExamples
  pod 'FelgoIOS', :git => 'https://github.com/FelgoSDK/FelgoIOS.git'

end
